version: '2'

services:
  activity:
    build: .
    links:
      - cassandra
      - rabbitmq
    ports:
      - "1234:8000"

  worker:
    build: .
    links:
      - cassandra
      - rabbitmq
    environment:
      - C_FORCE_ROOT=1
    command: celery -A activity worker -l info

  cassandra:
    image: cassandra:3.9

  rabbitmq:
    image: rabbitmq:3.6.6
